server:
  bugsnag:
    api_key:
    release_stage:
  max_mind_database_dir: "./share"
  prefork: false
  internal:
    handler_proc_size: 16
    consumer_per_instance_size: 2
    consumer_queue_handler_size: 16
    debug: false
    buf_flush_interval: 5000
    buf_size: 5000
    ch_write_timeout: 0m15s
    metric_table: appmetrica.events
    with_geo: true
  clickhouse:
    hosts:
      - localhost:9001
    username:
    database:
    password:
    max_execution_time: 30
    max_open_conns: 20
    max_idle_conns: 15
    max_conn_max_lifetime: 10m0s
  kafka_reader:
    brokers: [":9993", ":9994", ":9995"]
    group_id: "appmetrica_main_readers"
    group_topics: []
    topic: "appmetrica_main_bus"
    partition: 0
    queuecapacity: 0
    minbytes: 0
    maxbytes: 010e6 #10MB
    maxwait: 0s
    readbatchtimeout: 0s
    readlaginterval: 0s
  kafka_writer:
    brokers: [":9993", ":9994", ":9995"]
    topic: "appmetrica_main_bus"
    maxattempts: 0
    writebackoffmin: 0s
    writebackoffmax: 0s
    batchsize: 0
    batchbytes: 0
    batchtimeout: 0s
    readtimeout: 0s
    writetimeout: 0s
    async: false